DROP TABLE *;

CREATE TABLE movie(
    id INT NOT NULL AUTO_INCREMENT,
    title VARCHAR(100) NOT NULL,
    year VARCHAR(100) NOT NULL,
    director VARCHAR(100) NOT NULL,
    score INT NOT NULL,
    PRIMARY KEY (id)
);